authors:
  fb:
    name: Florian Buetow
    description: Author
    avatar: https://avatars.githubusercontent.com/u/2320560?v=4
    url: https://x.com/intent/follow?screen_name=bytetweets
  pb:
    name: Paul Bütow
    description: Featured
    avatar: https://foo.zone/about/paul.jpg
    url: https://foo.zone/about/
